### ISSUE TITLE
SQL injection in create_access_list_markup()

### ISSUE THREAD

**Issue by mudrd8mz** [YU-MITC/moodle-mod_kalmediares#2]
The function `create_access_list_markup()` passes the parameters $sort and $order directly into the SQL query. This is a serious SQL injection risk. Always use placeholders in custom SQL queries (? or :named). Please refer to https://docs.next.moodle.org/dev/Security:SQL_injection

**Comment by YU-MITC** [comment]
Thanks  mudrd8mz.
We modified SQL queries in this plugin.
